### ISSUE TITLE
Apostrophes in decision categories break things

### ISSUE THREAD

**Issue by Jeff-Thompson12** [pharmaR/riskassessment#523]
I noticed if there is an apostrophe in a decision category name, everything falls apart, which is surprising because I thought we switched over to `glue::glue_sql()`:

```yml
decisions:
    categories:
      - Super GxP Compliant
      - It's okay
      - Pending Review
      - Not Promising
      - Terrible pkg
```

Console:

![image](https://github.com/pharmaR/riskassessment/assets/17878953/7ffe6e9e-7573-4562-a5f8-8524f444bb22)

App:

![image](https://github.com/pharmaR/riskassessment/assets/17878953/480c3877-a645-44fa-a430-50e8da8ea3d8)
