### ISSUE TITLE
"Viewer" role & "comment" privilege

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#564]
I'm thinking about the prospect of having a user role where they can't do anything. Literally, all they can do is view/ observe the deployed app, navigating from tab to tab, but perhaps we don't want them to even comment. If that's the case, we should add "comment" as a new privilege where we could give users access to the comment modules located around the application.

I tested the following, and it looks like leaving a role's privilege bucket empty in the config file works well!
```yml
default:
  assessment_db: database.sqlite
  loggit_json: loggit.json
  credential_db: credentials.sqlite
  credentials:
    roles:
      - admin
      - lead
      - viewer
    privileges:
      admin: [admin, weight_adjust, auto_decision_adjust, final_decision, revert_decision, add_package, delete_package]
      lead: [weight_adjust, auto_decision_adjust, final_decision, revert_decision, add_package, delete_package]
      viewer: 
  decisions:
```
