### ISSUE TITLE
Globally specify metrics (or at least for Dependencies page)

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#604]
Once #480 is merged, it would be nice if the user could insert specific metrics into the table of interest. For example, if Vignettes, pkg downloads, and/or code coverage are really important to them, they could add them. This also could be a config file parameter, so related to #598. Could create something like this that toggles the score on or off, plus add's requested metrics

```
dependencies:
  auto_assess: FALSE
  metrics:
    - score
    - has_vignettes
    - covr_coverage
    - downloads_1yr
```

Or maybe those metrics could be used globally for other things in the app, so maybe they need their own section that could get sucked into other modules...

```
my_metrics:
  - has_vignettes
  - covr_coverage
  - downloads_1yr
dependencies:
  auto_assess: FALSE
```

Obviously, we could come up with a better name than my metrics. Maybe it's `display_metrics` or `include_metrics` or `validation_metrics` or `crucial_metrics`. Who knows!
