### ISSUE TITLE
Rescoring bugs

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskassessment#680]
When re-scoring, the `decision_by` and `decision_date` columns should be reset, since the decisions are also reset.

![image](https://github.com/pharmaR/riskassessment/assets/17878953/2447aa2f-ec2c-4b5c-9132-8be8eb351d67)

Also, some pkgs claim to have been auto-assigned a decision (prior to re-scoring) but they clearly were not, given the current db-config:

```yml
Medium Risk:
    - .3983
    - .6391
High Risk:
    - .6391
    - 1
```

![image](https://github.com/pharmaR/riskassessment/assets/17878953/fe83cbcc-f597-4603-9677-481bb67fa377)
